### ISSUE TITLE
插件不能用了,有什么替代方案么

### ISSUE THREAD

**Issue by xmt328** [taxigps/metadata.douban.com#6]
网上都说是豆瓣API不能用了
能不能直接爬取豆瓣页面上的数据做替换

**Comment by Dreamray** [comment]
翻墙配合TMDB可以用，插件设置成中文，还不错

**Comment by xmt328** [comment]
> 翻墙配合TMDB可以用，插件设置成中文，还不错

已经用jellyfin加翻墙解决了,谢谢

**Comment by Dreamray** [comment]
jellyfin没用过，比kodi好用吗

**Comment by xmt328** [comment]
可以网页端操作刮削失败的影片,而且可以多终端同步观看进度

**Comment by Dreamray** [comment]
局域网串流用的什么协议，支持dlna吗

**Comment by xmt328** [comment]
http(s),自行配置之后也可以支持smb nfs之类的, 支持dlna
网上很多kodi jellyfin的对比,你可以自己看下
